### ISSUE TITLE
GWT CSRF

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dernasherbrezon/csrf-filter#4]
```
i have gwt application and i would like to use your CSRF Filter, Could you 
please give me any advice how to add the ${csrf} to my gwt application.

appreciate your advice.

Thanks


```

Original issue reported on code.google.com by `loay.sa...@gmail.com` on 11 Mar 2014 at 3:20

**Comment by dernasherbrezon** [comment]
* put hidden field onto form: http://www.gwtproject.org/javadoc/latest/com/google/gwt/user/client/ui/Hidden.html
* use getThreadLocalRequest to get the csrf attribute and set as value on that field http://www.gwtproject.org/javadoc/latest/com/google/gwt/user/server/rpc/AbstractRemoteServiceServlet.html#getThreadLocalRequest()
